name = "demo-pinetime"
target = "thumbv7em-none-eabihf"
board = "pinetime"
chip = "../../chips/nRF52832.toml"
stacksize = 896

[kernel]
path = "."
name = "demo-pinetime"
requires = {flash = 30000, ram = 3072}
features = ["itm"]

[supervisor]
notification = 1

[outputs.flash]
address = 0x0000_0000
size = 0x0008_0000
read = true
execute = true

[outputs.ram]
address = 0x2000_0000
size = 0x0001_0000
read = true
write = true
execute = true

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.gpio]
path = "../../drv/nrf52832-gpio"
name = "drv-nrf52832-gpio"
priority = 1
requires = {flash = 1024, ram = 1024}
start = true
uses = ["gpio"]

#[tasks.spi]
#path = "../../drv/nrf52832-spi-server"
#name = "drv-nrf52832-spi-server"
#priority = 2
#requires = {flash = 16384, ram = 2048}
#uses = ["spitwi0"]
#start = true
#stacksize = 880
#task-slots = ["gpio"]
#
#[tasks.spi.config.spi]
#global_config = "spi0"

[tasks.lcd]
path = "../../task/pinetime-lcd"
name = "task-pinetime-lcd"
priority = 3
requires = {flash = 8192, ram = 2048}
start = true
task-slots = ["gpio"]
uses = ["spitwi0"]
stacksize = 1536

[tasks.hiffy]
path = "../../task/hiffy"
name = "task-hiffy"
priority = 3
requires = {flash = 8192, ram = 16384 }
stacksize = 2048
start = true

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 128, ram = 256}
stacksize = 256
start = true

[config]

[config.spi.spi0]
controller = 0

[config.spi.spi0.mux_options.lcd]
miso_pin = 4
mosi_pin = 3
sck_pin = 2

[config.spi.spi0.devices.lcd]
mux = "lcd"
cs = 25
frequency = "M8"
spi_mode = 3
